// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proton/spell_checker.proto

package proton

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpellCorrectorServiceClient is the client API for SpellCorrectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpellCorrectorServiceClient interface {
	Correction(ctx context.Context, in *SpellCorrectorInput, opts ...grpc.CallOption) (*SpellCorrectorOutput, error)
}

type spellCorrectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpellCorrectorServiceClient(cc grpc.ClientConnInterface) SpellCorrectorServiceClient {
	return &spellCorrectorServiceClient{cc}
}

func (c *spellCorrectorServiceClient) Correction(ctx context.Context, in *SpellCorrectorInput, opts ...grpc.CallOption) (*SpellCorrectorOutput, error) {
	out := new(SpellCorrectorOutput)
	err := c.cc.Invoke(ctx, "/proton.SpellCorrectorService/Correction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpellCorrectorServiceServer is the server API for SpellCorrectorService service.
// All implementations must embed UnimplementedSpellCorrectorServiceServer
// for forward compatibility
type SpellCorrectorServiceServer interface {
	Correction(context.Context, *SpellCorrectorInput) (*SpellCorrectorOutput, error)
}

// UnimplementedSpellCorrectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSpellCorrectorServiceServer struct {
}

func (UnimplementedSpellCorrectorServiceServer) Correction(context.Context, *SpellCorrectorInput) (*SpellCorrectorOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Correction not implemented")
}
func (UnimplementedSpellCorrectorServiceServer) mustEmbedUnimplementedSpellCorrectorServiceServer() {}

// UnsafeSpellCorrectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpellCorrectorServiceServer will
// result in compilation errors.
type UnsafeSpellCorrectorServiceServer interface {
	mustEmbedUnimplementedSpellCorrectorServiceServer()
}

func RegisterSpellCorrectorServiceServer(s grpc.ServiceRegistrar, srv SpellCorrectorServiceServer) {
	s.RegisterService(&SpellCorrectorService_ServiceDesc, srv)
}

func _SpellCorrectorService_Correction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpellCorrectorInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpellCorrectorServiceServer).Correction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proton.SpellCorrectorService/Correction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpellCorrectorServiceServer).Correction(ctx, req.(*SpellCorrectorInput))
	}
	return interceptor(ctx, in, info, handler)
}

// SpellCorrectorService_ServiceDesc is the grpc.ServiceDesc for SpellCorrectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpellCorrectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proton.SpellCorrectorService",
	HandlerType: (*SpellCorrectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Correction",
			Handler:    _SpellCorrectorService_Correction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proton/spell_checker.proto",
}
