// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proton/spell_checker.proto

package proton

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpellCorrectorInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SpellCorrectorInput) Reset() {
	*x = SpellCorrectorInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proton_spell_checker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpellCorrectorInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellCorrectorInput) ProtoMessage() {}

func (x *SpellCorrectorInput) ProtoReflect() protoreflect.Message {
	mi := &file_proton_spell_checker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellCorrectorInput.ProtoReflect.Descriptor instead.
func (*SpellCorrectorInput) Descriptor() ([]byte, []int) {
	return file_proton_spell_checker_proto_rawDescGZIP(), []int{0}
}

func (x *SpellCorrectorInput) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SpellCorrectorOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      string  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	IsCorrected bool    `protobuf:"varint,2,opt,name=is_corrected,json=isCorrected,proto3" json:"is_corrected,omitempty"`
	Probability float32 `protobuf:"fixed32,3,opt,name=probability,proto3" json:"probability,omitempty"`
	Language    string  `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *SpellCorrectorOutput) Reset() {
	*x = SpellCorrectorOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proton_spell_checker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpellCorrectorOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellCorrectorOutput) ProtoMessage() {}

func (x *SpellCorrectorOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proton_spell_checker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellCorrectorOutput.ProtoReflect.Descriptor instead.
func (*SpellCorrectorOutput) Descriptor() ([]byte, []int) {
	return file_proton_spell_checker_proto_rawDescGZIP(), []int{1}
}

func (x *SpellCorrectorOutput) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SpellCorrectorOutput) GetIsCorrected() bool {
	if x != nil {
		return x.IsCorrected
	}
	return false
}

func (x *SpellCorrectorOutput) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *SpellCorrectorOutput) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_proton_spell_checker_proto protoreflect.FileDescriptor

var file_proton_spell_checker_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x15, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x22, 0x91, 0x01, 0x0a, 0x16, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f,
	0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x32, 0x66, 0x0a, 0x15, 0x53, 0x70, 0x65, 0x6c, 0x6c,
	0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4d, 0x0a, 0x0a, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x6f,
	0x72, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proton_spell_checker_proto_rawDescOnce sync.Once
	file_proton_spell_checker_proto_rawDescData = file_proton_spell_checker_proto_rawDesc
)

func file_proton_spell_checker_proto_rawDescGZIP() []byte {
	file_proton_spell_checker_proto_rawDescOnce.Do(func() {
		file_proton_spell_checker_proto_rawDescData = protoimpl.X.CompressGZIP(file_proton_spell_checker_proto_rawDescData)
	})
	return file_proton_spell_checker_proto_rawDescData
}

var file_proton_spell_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proton_spell_checker_proto_goTypes = []interface{}{
	(*SpellCorrectorInput)(nil),  // 0: proton.Spell_corrector_input
	(*SpellCorrectorOutput)(nil), // 1: proton.Spell_corrector_output
}
var file_proton_spell_checker_proto_depIdxs = []int32{
	0, // 0: proton.SpellCorrectorService.Correction:input_type -> proton.Spell_corrector_input
	1, // 1: proton.SpellCorrectorService.Correction:output_type -> proton.Spell_corrector_output
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proton_spell_checker_proto_init() }
func file_proton_spell_checker_proto_init() {
	if File_proton_spell_checker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proton_spell_checker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpellCorrectorInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proton_spell_checker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpellCorrectorOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proton_spell_checker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proton_spell_checker_proto_goTypes,
		DependencyIndexes: file_proton_spell_checker_proto_depIdxs,
		MessageInfos:      file_proton_spell_checker_proto_msgTypes,
	}.Build()
	File_proton_spell_checker_proto = out.File
	file_proton_spell_checker_proto_rawDesc = nil
	file_proton_spell_checker_proto_goTypes = nil
	file_proton_spell_checker_proto_depIdxs = nil
}
